apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-prod
  labels:
    type: local
    environment: production
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-prod"
  persistentVolumeReclaimPolicy: Retain