apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bazarstore-prod
  labels:
    environment: production
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP  