apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bazarstore-dev
  labels:
    environment: development
type: Opaque
data:
  username: cG9zdGdyZXM=  
  password: cG9zdGdyZXM=  
