apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bazarstore-prod
  labels:
    environment: production
type: Opaque
data:
  username: cG9zdGdyZXM= 
  password: cG9zdGdyZXM=  