apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: bazarstore-prod
  labels:
    environment: production
spec:
  selector:
    app: core
  ports:
  - port: 80
    targetPort: 5005
    nodePort: 30005
  type: NodePort # Required for EKS external access
