apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http