apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarcom-config
  namespace: dev
data:
  POSTGRES_DB: bazarcom
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  DOCKER_ENV: "true"
  CATALOG_SERVICE_URL: "http://catalog-service:5000"
  ORDER_SERVICE_URL: "http://order-service:5001"
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  ENABLE_METRICS: "true"