apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: bazarstore-dev
  labels:
    app: core
    environment: development
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: youssefashraf265/bazarcom-core:latest
        ports:
        - containerPort: 5005
        env:
        - name: DOCKER_ENV
          value: "true"
        - name: CATALOG_SERVICE_URL
          value: "http://catalog:5000"
        - name: ORDER_SERVICE_URL
          value: "http://order:5001"
        resources:
          limits:
            memory: "512Mi"    # Increased from 256Mi
            cpu: "500m"        # Increased from 300m
          requests:
            memory: "256Mi"    # Increased from 128Mi
            cpu: "200m"        # Increased from 100m
        readinessProbe:
          httpGet:
            path: /
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: bazarstore-dev
  labels:
    environment: development
spec:
  selector:
    app: core
  ports:
  - port: 80
    targetPort: 5005
    nodePort: 30005
  type: NodePort #loadbalancer
