apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: youssefashraf265/bazarcom-core:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: bazarcom-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 5