apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: core
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      name: http