apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: bazarstore-dev
  labels:
    app: order
    environment: development
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: youssefashraf265/bazarcom-order:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: bazarstore-config
              key: order-db-url
        - name: DOCKER_ENV
          value: "true"
        resources:
          limits:
            memory: "512Mi"    # Increase from 256Mi
            cpu: "500m"        # Increase from 300m
          requests:
            memory: "256Mi"    # Increase from 128Mi
            cpu: "200m"        # Increase from 100m
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30  # Wait for app and DB to initialize
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30  # Increased to wait for DB
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60  # Increased to avoid premature failures
          periodSeconds: 15
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: bazarstore-dev
  labels:
    environment: development
spec:
  selector:
    app: order
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30011
  type: NodePort