apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: http