apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: bazarstore-prod
  labels:
    app: catalog
    environment: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: youssefashraf265/bazarcom-catalog:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: bazarstore-config
              key: catalog-db-url
        - name: DOCKER_ENV
          value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"      
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30  # Increased wait time for DB connection
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30  # Increased to wait for DB
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60  # Increased to avoid premature failures
          periodSeconds: 15
          timeoutSeconds: 3