apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: bazarstore-prod
  labels:
    environment: production
spec:
  selector:
    app: catalog
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP 